### ISSUE TITLE
Potential Swing thread access violation errors in s3dropbox

### ISSUE THREAD

**Issue by saizhang** [tomcz/s3dropbox#1]
Hi there-

I am writing an automated tool to find potential errors in software. I used it to check
the "single thread rule" in Swing applications, e.g., all GUI objects must be accessed
from the "event dispatch thread", and found there may be a few potential violations in
s3dropbox's code base.

Here is one example:

in class: com.tomczarniecki.s3.gui.DeleteBucketAction

private void deleteBucket() {
        executor.execute(new Runnable() {              //(1)
            public void run() {
                try {
                    controller.deleteCurrentBucket();      //(2)
                } catch (Exception e) {
                    logger.info("Delete failed", e);
                    deleteError();                                         //(3)
                }
            }
        });
    }

```
private void deleteError() {
    String text = "Cannot delete folder %s.\nPlease make sure that it is empty and try again.";
    display.showErrorMessage("Delete failed", String.format(text, controller.getSelectedBucketName()));   //(4)
}
```

(1) spawns a new thread, which aims to delete the current buckets at (2). However, it there is an exception the deleteError code at (3) will directly access UI object at (4).

Inside (4), the showErrorMessage method will eventually call:  JOptionPane.showMessageDialog, which is not thread-safe in swing. In other words, that method should only be called via the event dispatch thread (EDT).

As indicated by Swing's documentation. Swing is a single-threaded UI toolkit. Because it is not thread-safe, all Swing code must be executed in the EDT. As the official documentation states, invoking Swing code from multiple threads risks thread interference or memory-consistency errors.  In addition, Swing does not provide any run-time checks for correct EDT usage and, most of the time, you can get away with an apparently "well behaved" Swing UI that breaks these rules.

I also note other places in s3dropbox already take care of this rule, such as:
inside DropboxTableModel.java

private void updateView() {
        worker.executeOnEventLoop(new Runnable() {
            public void run() {
                fireTableDataChanged();
            }
        });
    }

It explicitly update the UI inside the event loop. So, technically, the error displaying code should also be executed inside the event loop (though the app may "behave" well now).

How do you think about such  potential errors? Any comments, suggestion are highly appreciated; and will help us improve the tool.

I also have a number of reported errors, I am also willing to post them here.

Thanks a lot

-Sai

**Comment by tomcz** [comment]
Sai, thanks for that. Please post these issues here and I can take a look to see how important they are to fix.

**Comment by saizhang** [comment]
Thanks Tom. Let me organize the reported issues and will  post them here later.

  Btw. Do you think such a tool (finding violations for the single-thread rule in Swing) would be valuable  for developing multithread UI applications in practice?  Is it easy to violate the single-thread rule based on your experience?

 In my viewpoint, it would be easy to violate such rule, particularly when Swing does not have an explicit check. But such violation may even lead to unpredictable behaviors (particularly in the multicore era).  The tool we are developing stem from a research project. Now, we are improving that to scale to larger programs!  Any comments, suggestion, and experience sharing are highly appreciated!

**Comment by tomcz** [comment]
Checkstyle already does a lot of this kind of checking so rather than writing a whole new tool how about writing a plugin to checkstyle? Reporting on violations is fine but what is more important are the pracitces and patterns that need to be adopted to make it easier to avoid the issue in the first place. That is why there is a Worker interface in this project, and yes I failed to use it in your example code.

On the other hand, you could use aspect programming to enforce this behaviour at runtime. That way no tool would be required. That may be taking it too far as it will be too much magic.

**Comment by saizhang** [comment]
Thanks a lot, Tom, for your valuable comments.

We have considered these options when designing the tool. 

Runtime checking (e.g., using AOP or others) is a good way to find the errors, but it can NOT explore EVERY possible path that may lead to a violation. In other words, it can only report violations that have already been exhibited in certain executions, but can not find potential errors, which may only be covered by some very specific scenarios.  In addition, I suspect that there is not a straightforward way to avoid this program. e.g, you can not replace every GUI object accessing by either async execution or sync execution, since async execution has timing issues, while sync execution may lead to deadlock. So that, using AOP to enforce the behavior at runtime may not be a perfect solution.

Other the other hand, Checkstyle seems to focus more on general Java coding styles, such as duplicate code, naming issues, and comments. However, it does not have an infrastructure to systematically analysis the calling relations in a program (e.g., how can it decide a method is invoked from a EDT?), and to my best knowledge, there may not be any generally applicable patterns to avoid (or find) such violations. So, a whole-program analysis is necessary.

Our tool uses pure static analysis to reason about every possible behavior in a program, and report suspicious code access issues even if that part of code has very low chance to be executed in practice. I think that may be the major disadvantage in employing static analysis.

**Comment by tomcz** [comment]
Runtime checking - this is why tests are more important. I prefer to rely on those rather than static-analysis tools. Interestingly I do use static analysis tools in my day job when asked to review codebases. Even then I tend to only use the results from these tools as indicators of the health of a codebase rather than "proof" of errors - I tend to compare the ouptut of these tools against "clean" projects in the open source space so I at least have a baseline of what I feel is acceptable, and that differs between clients & contexts. Tools like findbugs tend to have more false-negatives (or at least report issues where I feel there is none).
