### ISSUE TITLE
S3DropBox” is damaged and can’t be opened. You should eject the disk image.

### ISSUE THREAD

**Issue by sobytes** [tomcz/s3dropbox#2]
Hi Tom

Just letting you know i downloaded your mac.dmg and tried to open it and i get the following error please see the screenshot.

![screen shot 2013-12-09 at 13 02 10](https://f.cloud.github.com/assets/2689776/1704839/447cbada-60d2-11e3-8296-6cc058a70487.png)

Just so you know my setup i have just updated mountain lion i am running Software  OS X 10.9 and have updated to maverick

Thanks

Sam

**Comment by tomcz** [comment]
Hi Sam,
Thanks for the heads-up. I've repackaged the latest dmg on maverick. It seems to work fine for me now. Could you please try again?
Thanks,
Tom.

**Comment by sobytes** [comment]
Hi Tom

Have you got a link to the new one i have tried the one in the readme and i am still getting the same error i might be downloading the wrong one.

Thanks

**Comment by tomcz** [comment]
Hmm, it looks like downloads from watchitlater.com are getting corrupted. I've moved the downloads to S3. Try using https://s3.amazonaws.com/watchitlater/S3DropBox-20131209.dmg to fetch the DMG.

**Comment by sobytes** [comment]
![screen shot 2013-12-09 at 15 28 53](https://f.cloud.github.com/assets/2689776/1705922/ef66d1e2-60e6-11e3-965d-462b7298ae92.png)
Hi Tom

Sill getting the same error unfortunately screenshot attached.

Thanks

Sam

On Mon, Dec 9, 2013 at 3:26 PM, Tom Czarniecki notifications@github.comwrote:

> Hmm, it looks like downloads from watchitlater.com are getting corrupted.
> I've moved the downloads to S3. Try using
> https://s3.amazonaws.com/watchitlater/S3DropBox-20131209.dmg to fetch the
> DMG.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/tomcz/s3dropbox/issues/2#issuecomment-30140623
> .

## 

_Samuel East_ - Director

samuel.east@sobytes.com info@makeandsee.com

## Connect with me on linkedinhttp://uk.linkedin.com/pub/samuel-east/30/94a/2a7/

_www.sobytes.com http://www.samueleast.co.uk/_

07446 276 026
ICE Britannia House, Caerphilly Business Park / Van Rd / Caerphilly / CF83
8GG

**Comment by tomcz** [comment]
Ok, that is weird. Can you try a command line tool like curl or wget to download it? I just tired with wget and it downloaded, opened and ran without any problems.

**Comment by sobytes** [comment]
ok no problem ill try now

**Comment by sobytes** [comment]
Hi tom

Worked straight away using wget to download weird.

Working now tho

**Comment by sobytes** [comment]
Hi Tom

One last question would you be able to slightly modify this for a price for a customised version if i gave you a brief would you be able to give a rough quote?

Thanks

Sam

**Comment by tomcz** [comment]
What modifications are you looking for?

**Comment by sobytes** [comment]
whats the best email to contact you on so i can give you some more information?

**Comment by tomcz** [comment]
ripper AT tomczarniecki DOT com
